# Generated by Django 4.1.3 on 2022-11-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dept', models.CharField(max_length=255)),
                ('m_id', models.CharField(max_length=14)),
                ('admission_date', models.DateField()),
                ('admission_year', models.CharField(choices=[('', 'Select Year'), (2022, 2022), (2021, 2021), (2020, 2020), (2019, 2019), (2018, 2018), (2017, 2017), (2016, 2016), (2015, 2015), (2014, 2014), (2013, 2013), (2012, 2012), (2011, 2011), (2010, 2010), (2009, 2009), (2008, 2008), (2007, 2007), (2006, 2006), (2005, 2005), (2004, 2004), (2003, 2003), (2002, 2002)], max_length=14)),
                ('user_type', models.CharField(choices=[('Student', 'Student'), ('Employee', 'Employee')], default='Student', max_length=25)),
                ('employee_role', models.CharField(choices=[('empty', '-----------'), ('Web Development', 'Web Development'), ('App Development', 'App Development')], default='empty', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
