# Generated by Django 4.1.3 on 2022-11-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='m_id',
            field=models.CharField(max_length=25),
        ),
    ]
