# Generated by Django 4.1.3 on 2022-11-02 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_student_m_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='m_id',
            new_name='str_id',
        ),
    ]
